# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c7cbedddd43c8d4c6e9b3afa427994f7"
name = "Paws & Effect (Dev)"
application_url = "https://paws-and-effect-git-develop-willowsoftstudio-5437s-projects.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/api/webhooks/orders-create"

[access_scopes]
scopes = "write_products,read_products,write_customers,read_customers,write_draft_orders,write_validations,read_validations"

[auth]
redirect_urls = [
  "https://paws-and-effect-git-develop-willowsoftstudio-5437s-projects.vercel.app/api/auth/callback"
]
