# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5e33f10ff81d0679af7583e5ab5aac13" # Paste your Production Client ID here
name = "Paws & Effect"
application_url = "https://paws-and-effect.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/api/webhooks/orders-create"

[access_scopes]
scopes = "write_products,read_products,write_customers,read_customers,write_draft_orders,write_validations,read_validations"

[auth]
redirect_urls = [
  "https://paws-and-effect.vercel.app/api/auth/callback"
]
