# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = ""
name = "Paws & Effect"
application_url = "https://localhost:3001"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
scopes = "write_products,read_products,write_customers,read_customers,write_draft_orders"

[auth]
redirect_urls = [
  "https://localhost:3001/api/auth/callback"
]
