AWSTemplateFormatVersion: '2010-09-09'
Description: 'Provision a secure, private Amazon S3 Bucket with dynamic bucket naming for Paws & Effect Prescription Uploads.'

Parameters:
  BucketName:
    Type: String
    Description: 'Unique name for your S3 bucket.'
  ApplicationUrl:
    Type: String
    Description: 'The application URL from your active shopify.app.toml.'

Resources:
  PrescriptionS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - HEAD
            AllowedOrigins:
              - !Ref ApplicationUrl
              - 'http://localhost:3001'
            ExposedHeaders:
              - ETag
            MaxAge: 3000

Outputs:
  BucketName:
    Description: 'Name of the secure prescription S3 bucket.'
    Value: !Ref PrescriptionS3Bucket
  BucketARN:
    Description: 'ARN of the secure prescription S3 bucket.'
    Value: !GetAtt PrescriptionS3Bucket.Arn
  BucketDomainName:
    Description: 'Domain Name of the secure prescription S3 bucket.'
    Value: !GetAtt PrescriptionS3Bucket.DomainName
