api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "prescription-validator"
type = "function"
uid = "dd0192a8-532d-0fbf-f636-604aa8591f5df46ec97b"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
